### ISSUE TITLE
moving s3 bucket from test to main

### ISSUE THREAD

**Issue by chaitanyareddyk** [iprhub/iprhub-project-portal#42]
Before deployment, its better to change the bucket name in s3 for file attachments

**Comment by meher345** [comment]
Will create three different buckets for dev, staging and prod

**Comment by meher345** [comment]
Refer #50

**Comment by meher345** [comment]
created bucket for prod "iprhub"

@chaitanyareddyk please create an account in app.iprhub.io for yourself as creator and test attachment functionality and see if its getting uploaded to the right bucket.

**Comment by chaitanyareddyk** [comment]
![S3 CORS policy error](https://user-images.githubusercontent.com/18068142/65038406-80f95f80-d96d-11e9-912c-3f46d41ed7d1.png)

**When clicked on upload button after selecting file, the file didn't uploaded and thrown this error**
