### ISSUE TITLE
Slow render in some places [retest after deployment]

### ISSUE THREAD

**Issue by chaitanyareddyk** [iprhub/iprhub-project-portal#45]
Opening idf form from /protect taking too much time to render. same with submit button on idf/preview page. Must retest this bug after deployment.

**Comment by meher345** [comment]
Please test in staging why this is hapenning. If the issue still exists then we need to find a way to solve this.

**Comment by chaitanyareddyk** [comment]
This issue doesn't exists in staging at staging.iprhub.io
