### ISSUE TITLE
Allow users to go private

### ISSUE THREAD

**Issue by chaitanyareddyk** [iprhub/iprhub-project-portal#49]
Allow users to make their profiles private

**Comment by meher345** [comment]
**center-forward:**

- [] Mark my profile as private [checkbox - Input]
- Also have a provision to display some tooltip or some message (ex: You profile will not be searchable on the, however users can send invitations using your email)
- Capture this data during on boarding and also be able to update in settings.

**back-boy**

- Add a new field on User db table [ **isPrivate** @-boolean(default: false) ]
- Update user mutation and query to store and retrieve this field.
